require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MumscrapurlsController do

  # This should return the minimal set of attributes required to create a valid
  # Mumscrapurl. As you add validations to Mumscrapurl, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "tkurl" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MumscrapurlsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mumscrapurls as @mumscrapurls" do
      mumscrapurl = Mumscrapurl.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mumscrapurls).should eq([mumscrapurl])
    end
  end

  describe "GET show" do
    it "assigns the requested mumscrapurl as @mumscrapurl" do
      mumscrapurl = Mumscrapurl.create! valid_attributes
      get :show, {:id => mumscrapurl.to_param}, valid_session
      assigns(:mumscrapurl).should eq(mumscrapurl)
    end
  end

  describe "GET new" do
    it "assigns a new mumscrapurl as @mumscrapurl" do
      get :new, {}, valid_session
      assigns(:mumscrapurl).should be_a_new(Mumscrapurl)
    end
  end

  describe "GET edit" do
    it "assigns the requested mumscrapurl as @mumscrapurl" do
      mumscrapurl = Mumscrapurl.create! valid_attributes
      get :edit, {:id => mumscrapurl.to_param}, valid_session
      assigns(:mumscrapurl).should eq(mumscrapurl)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mumscrapurl" do
        expect {
          post :create, {:mumscrapurl => valid_attributes}, valid_session
        }.to change(Mumscrapurl, :count).by(1)
      end

      it "assigns a newly created mumscrapurl as @mumscrapurl" do
        post :create, {:mumscrapurl => valid_attributes}, valid_session
        assigns(:mumscrapurl).should be_a(Mumscrapurl)
        assigns(:mumscrapurl).should be_persisted
      end

      it "redirects to the created mumscrapurl" do
        post :create, {:mumscrapurl => valid_attributes}, valid_session
        response.should redirect_to(Mumscrapurl.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mumscrapurl as @mumscrapurl" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mumscrapurl.any_instance.stub(:save).and_return(false)
        post :create, {:mumscrapurl => { "tkurl" => "invalid value" }}, valid_session
        assigns(:mumscrapurl).should be_a_new(Mumscrapurl)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mumscrapurl.any_instance.stub(:save).and_return(false)
        post :create, {:mumscrapurl => { "tkurl" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mumscrapurl" do
        mumscrapurl = Mumscrapurl.create! valid_attributes
        # Assuming there are no other mumscrapurls in the database, this
        # specifies that the Mumscrapurl created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mumscrapurl.any_instance.should_receive(:update_attributes).with({ "tkurl" => "MyString" })
        put :update, {:id => mumscrapurl.to_param, :mumscrapurl => { "tkurl" => "MyString" }}, valid_session
      end

      it "assigns the requested mumscrapurl as @mumscrapurl" do
        mumscrapurl = Mumscrapurl.create! valid_attributes
        put :update, {:id => mumscrapurl.to_param, :mumscrapurl => valid_attributes}, valid_session
        assigns(:mumscrapurl).should eq(mumscrapurl)
      end

      it "redirects to the mumscrapurl" do
        mumscrapurl = Mumscrapurl.create! valid_attributes
        put :update, {:id => mumscrapurl.to_param, :mumscrapurl => valid_attributes}, valid_session
        response.should redirect_to(mumscrapurl)
      end
    end

    describe "with invalid params" do
      it "assigns the mumscrapurl as @mumscrapurl" do
        mumscrapurl = Mumscrapurl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mumscrapurl.any_instance.stub(:save).and_return(false)
        put :update, {:id => mumscrapurl.to_param, :mumscrapurl => { "tkurl" => "invalid value" }}, valid_session
        assigns(:mumscrapurl).should eq(mumscrapurl)
      end

      it "re-renders the 'edit' template" do
        mumscrapurl = Mumscrapurl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mumscrapurl.any_instance.stub(:save).and_return(false)
        put :update, {:id => mumscrapurl.to_param, :mumscrapurl => { "tkurl" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mumscrapurl" do
      mumscrapurl = Mumscrapurl.create! valid_attributes
      expect {
        delete :destroy, {:id => mumscrapurl.to_param}, valid_session
      }.to change(Mumscrapurl, :count).by(-1)
    end

    it "redirects to the mumscrapurls list" do
      mumscrapurl = Mumscrapurl.create! valid_attributes
      delete :destroy, {:id => mumscrapurl.to_param}, valid_session
      response.should redirect_to(mumscrapurls_url)
    end
  end

end
