require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PunescrapurlsController do

  # This should return the minimal set of attributes required to create a valid
  # Punescrapurl. As you add validations to Punescrapurl, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "tkurl" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PunescrapurlsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all punescrapurls as @punescrapurls" do
      punescrapurl = Punescrapurl.create! valid_attributes
      get :index, {}, valid_session
      assigns(:punescrapurls).should eq([punescrapurl])
    end
  end

  describe "GET show" do
    it "assigns the requested punescrapurl as @punescrapurl" do
      punescrapurl = Punescrapurl.create! valid_attributes
      get :show, {:id => punescrapurl.to_param}, valid_session
      assigns(:punescrapurl).should eq(punescrapurl)
    end
  end

  describe "GET new" do
    it "assigns a new punescrapurl as @punescrapurl" do
      get :new, {}, valid_session
      assigns(:punescrapurl).should be_a_new(Punescrapurl)
    end
  end

  describe "GET edit" do
    it "assigns the requested punescrapurl as @punescrapurl" do
      punescrapurl = Punescrapurl.create! valid_attributes
      get :edit, {:id => punescrapurl.to_param}, valid_session
      assigns(:punescrapurl).should eq(punescrapurl)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Punescrapurl" do
        expect {
          post :create, {:punescrapurl => valid_attributes}, valid_session
        }.to change(Punescrapurl, :count).by(1)
      end

      it "assigns a newly created punescrapurl as @punescrapurl" do
        post :create, {:punescrapurl => valid_attributes}, valid_session
        assigns(:punescrapurl).should be_a(Punescrapurl)
        assigns(:punescrapurl).should be_persisted
      end

      it "redirects to the created punescrapurl" do
        post :create, {:punescrapurl => valid_attributes}, valid_session
        response.should redirect_to(Punescrapurl.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved punescrapurl as @punescrapurl" do
        # Trigger the behavior that occurs when invalid params are submitted
        Punescrapurl.any_instance.stub(:save).and_return(false)
        post :create, {:punescrapurl => { "tkurl" => "invalid value" }}, valid_session
        assigns(:punescrapurl).should be_a_new(Punescrapurl)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Punescrapurl.any_instance.stub(:save).and_return(false)
        post :create, {:punescrapurl => { "tkurl" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested punescrapurl" do
        punescrapurl = Punescrapurl.create! valid_attributes
        # Assuming there are no other punescrapurls in the database, this
        # specifies that the Punescrapurl created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Punescrapurl.any_instance.should_receive(:update_attributes).with({ "tkurl" => "MyString" })
        put :update, {:id => punescrapurl.to_param, :punescrapurl => { "tkurl" => "MyString" }}, valid_session
      end

      it "assigns the requested punescrapurl as @punescrapurl" do
        punescrapurl = Punescrapurl.create! valid_attributes
        put :update, {:id => punescrapurl.to_param, :punescrapurl => valid_attributes}, valid_session
        assigns(:punescrapurl).should eq(punescrapurl)
      end

      it "redirects to the punescrapurl" do
        punescrapurl = Punescrapurl.create! valid_attributes
        put :update, {:id => punescrapurl.to_param, :punescrapurl => valid_attributes}, valid_session
        response.should redirect_to(punescrapurl)
      end
    end

    describe "with invalid params" do
      it "assigns the punescrapurl as @punescrapurl" do
        punescrapurl = Punescrapurl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Punescrapurl.any_instance.stub(:save).and_return(false)
        put :update, {:id => punescrapurl.to_param, :punescrapurl => { "tkurl" => "invalid value" }}, valid_session
        assigns(:punescrapurl).should eq(punescrapurl)
      end

      it "re-renders the 'edit' template" do
        punescrapurl = Punescrapurl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Punescrapurl.any_instance.stub(:save).and_return(false)
        put :update, {:id => punescrapurl.to_param, :punescrapurl => { "tkurl" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested punescrapurl" do
      punescrapurl = Punescrapurl.create! valid_attributes
      expect {
        delete :destroy, {:id => punescrapurl.to_param}, valid_session
      }.to change(Punescrapurl, :count).by(-1)
    end

    it "redirects to the punescrapurls list" do
      punescrapurl = Punescrapurl.create! valid_attributes
      delete :destroy, {:id => punescrapurl.to_param}, valid_session
      response.should redirect_to(punescrapurls_url)
    end
  end

end
